name: Upload to Discord
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
    - name: Build with Gradle
      run: ./gradlew build
    - name: Send Message and Files to Discord
      uses: MineBartekSA/discord-webhook@v2
      with:
        webhook: "${{ secrets.WEBHOOK_URL }}?thread_name='[${{ github.event.head_commit.tree_id }}] ${{ github.event.after }}'"
        content: ${{ github.event.commits }}
        attachments: |
          - file: ./fabric/build/libs/witchery-fabric-[0-9].[0-9].[0-9a-zA-Z]+.jar
          - file: ./neoforge/build/libs/witchery-neoforge-[0-9].[0-9].[0-9a-zA-Z]+.jar
